### PR TITLE
Week2

### PR DESCRIPTION
**Pull request by elena-sek**
Added functions and the shiny app.

### CODE REVIEW

**Comment by jasmin131** [comment]
Very nicely done. It is clear that you made progress compared to last week, added functions, updated the shiny app and the description file. The functions seem clear and are documented well with a title, description, parameters, and examples.

**Review by yassieq — COMMENTED** [review]
You made good progress on your code. Your code is clear and functions are well documented. Nice that the user is able to generate both a productivity plot and productivity report. A small comment on the tasks_given_availability function, you give an example usage. However, this example does not include a start time or end time, which would be nice to include. Additionally, it could maybe be nice for the user to get a warning message if the entered start and end time are not valid numbers.

**Comment by jasmin131** [comment]
(according to GitHub my last review did not count as a review so here we go again ;)) Very nicely done. It is clear that you made progress compared to last week, added functions, updated the shiny app and the description file. The functions seem clear and are documented well with a title, description, parameters, and examples. I like that you set default values for the start and end time in the shiny app but I agree with @yassieq that perhaps adding a conditional statement to check whether the times are entered in the correct format or are even correct times would make your app even more robust. Overall, very nice job!

**Review by jasmin131 — COMMENTED** [review]
(according to GitHub my last review did not count as a review so here we go again ;)) Very nicely done. It is clear that you made progress compared to last week, added functions, updated the shiny app and the description file. The functions seem clear and are documented well with a title, description, parameters, and examples. I like that you set default values for the start and end time in the shiny app but I agree with @yassieq that perhaps adding a conditional statement to check whether the times are entered in the correct format or are even correct times would make your app even more robust. Overall, very nice job!

**Pull request merged**
